# Generated by Django 2.2.16 on 2023-01-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20230122_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Введите текст комментария, не более 200 символов', max_length=200, verbose_name='Текст комментария'),
        ),
    ]
